### ISSUE TITLE
Record._check_fields() does not check float or datetime fields

### ISSUE THREAD

**Issue by gregcorbett** [apel/apel#128]
This leads to `'None'` being passed to the database, rather than a correctly typed value (or `NULL`)

This is allowed (by default) in MySQL 5.1 and rather than fail it interprets `'None'` as the zero value for that data type (i.e. `0.00` for floats and `00/00/00 00:00:00` for datetimes). 

In MySQL 5.6.X this is not the default, as such records missing a datetime or float field will not be loaded.

**Comment by gregcorbett** [comment]
I've created a [new branch](https://github.com/gregcorbett/apel/tree/type_checking) with a [new test](https://github.com/gregcorbett/apel/blob/type_checking/test/test_cloud_record.py#L189) to illustrate [the issue](https://travis-ci.org/gregcorbett/apel/jobs/216764198). 

It uses the cloud test record because that was where the problem was first noticed, but it is probaly present in all records, as they all inherit `_check_fields()` from `Record`.

**Comment by tofu-rocketry** [comment]
What was the MySQL setting that you said was causing this?

**Comment by gregcorbett** [comment]
`sql_mode`, in 5.1 it is set to `''` and in 5.6.X it is set to `STRICT_TRANS_TABLES,NO_ENGINE_SUBSTITUTION`.

Globally (and persistently with respect to mysql server restarts) setting `sql_mode` to `''` in 5.6.X is a short term fix.

**Comment by tofu-rocketry** [comment]
MariaDB 10.1.19 doesn't have strict set, though later versions do.

**Comment by gregcorbett** [comment]
Shall I add similar tests to `test_load_from_msg_type_check` for Storage and Job Records?

**Comment by gregcorbett** [comment]
Having tried to implement them I don't think they are worth it. 

The test checks that missing values get correctly typed, such as `Benchmark` when we get sent a Cloud v0.2 record (so as not to rely on MySQL type casting). There isn't a similar case for Storage and Grid, but new tests could be based off of `CloudRecordTest.test_load_from_msg_type_check` when the Record format update happens.
