### ISSUE TITLE
Wrong SLURM field used for CpuDuration

### ISSUE THREAD

**Issue by tofu-rocketry** [apel/apel#160]
From GGUS: [ICM](https://ggus.eu/index.php?mode=ticket_info&ticket_id=132922), [BelGrid-UCL](https://ggus.eu/index.php?mode=ticket_info&ticket_id=132925), and [UKI-LT2-QMUL](https://ggus.eu/index.php?mode=ticket_info&ticket_id=132929)

`slurm_acc.sh` currently uses `CPUTimeRAW` from `sacct`, which is elapsed time * number of CPUs. This results in Elapsed time being the same as the wall clock time.

What should be used is probably `TotalCPU`, which is the sum of the SystemCPU and UserCPU time used by the job. However, parsing this field is less trivial than `CPUTimeRAW` as it seems to use a format which is something like `dd-hh:mm:ss`.

**Comment by pavel-demin** [comment]
> it seems to use a format which is something like `dd-hh:mm:ss`

The format depends on the time value. It can be one of the following:
 - `dd-hh:mm:ss`
 - `hh:mm:ss`
 - `mm:ss.SSS`

Here are a few examples that were requested via the GGUS ticket.

> format=JobID,JobName,User,Group,Start,End,Elapsed,CPUTimeRAW,Partition,NCPUS,NNodes,NodeList,MaxRSS,MaxVMSize,State
```
5940815|cream_877733810|user1|group1|2018-06-03T02:11:12|2018-06-05T03:36:08|2-01:24:56|1423168|partition|8|1|wn1|||COMPLETED
5961074|cream_538395496|user2|group2|2018-06-05T13:30:17|2018-06-05T14:40:05|01:09:48|4188|cpartition|1|1|wn2|||COMPLETED
5979785|cream_636487219|user3|group3|2018-06-05T14:59:34|2018-06-05T15:02:59|00:03:25|205|partition|1|1|wn3|||COMPLETED
```
> format=JobID,JobName,User,Group,Start,End,Elapsed,TotalCPU,Partition,NCPUS,NNodes,NodeList,MaxRSS,MaxVMSize,State
```
5940815|cream_877733810|user1|group1|2018-06-03T02:11:12|2018-06-05T03:36:08|2-01:24:56|8-15:40:36|partition|8|1|wn1|||COMPLETED
5961074|cream_538395496|user2|group2|2018-06-05T13:30:17|2018-06-05T14:40:05|01:09:48|01:09:18|partition|1|1|wn2|||COMPLETED
5979785|cream_636487219|user3|group3|2018-06-05T14:59:34|2018-06-05T15:02:59|00:03:25|01:05.753|partition|1|1|wn3|||COMPLETED 
```

**Comment by tofu-rocketry** [comment]
Thanks for the examples and info.
