### ISSUE TITLE
Install via setup.py fails, wants to install scripts/update_schema.sql

### ISSUE THREAD

**Issue by gregcorbett** [apel/apel#165]
[`setup.py`](https://github.com/apel/apel/blob/dev/setup.py#L59) wants to install `scripts/update_schema.sql`

But `scripts/update_schema.sql` doesn't exist as it was renamed to include version numbers (and now there are multiple versions of it.

This causes `python setup.py install` to fail.

Possible solutions:
- Wild card it like we did in the spec file.
- Don't include the update scripts in an install via `setup.py`.
- Have a post test step in TravisCI that tries to install via `setup.py`.

**Comment by tofu-rocketry** [comment]
Yes, we should add a CI test for this. It may also be better to do it the "correct" way round and do the setup first then run tests. Not sure at the moment.

Including the scripts by wildcard seems to be a good place to start so that it matches the SPEC file.

**Comment by gregcorbett** [comment]
I made a [branch](https://github.com/gregcorbett/apel/tree/issue-165) fixing the issue and starting to tackle doing the CI testing the right way around.

- The first commit is a general improvement to the script I could separate out as its own PR maybe.
- The second commit fixes the issue
- The third gets to the stage where APEL is installed via `setup.py` as part of CI testing, it feels slightly hacky - but I'm not sure how to get around that.
- The fourth commit tries to run the tests via `setup.py` as well and that causes `test/test_mysql.py` to hang indefinitely both locally and on Travis...

**Comment by gregcorbett** [comment]
as discussed, I've captured the outstanding opportunities for improvement [here](https://github.com/orgs/apel/projects/1#card-13959186).
