### ISSUE TITLE
Rewrite datetime functions

### ISSUE THREAD

**Issue by stuartpullinger** [apel/apel#17]
Our current iso2seconds function uses regular expressions to parse iso8601 durations. This does not support all of the standard such as fractional seconds. We could rewrite it to use the isoduration.parse_duration method in the python-isodate module.

We could also see whether we could remove the dependency on the iso8601 module and replace its functionality with the isodate module.

https://pypi.python.org/pypi/isodate

(Obviously, this involves changing the dependencies in the rpm too).

**Comment by tofu-rocketry** [comment]
`python-iso8601` available in EPEL for EL 5 to 7.
`python-isodate` only available in EPEL for EL 6 and 7.

So it may not be a good idea to replace `iso8601` just yet.

**Comment by tofu-rocketry** [comment]
Immediate problem is fixed. Not worth replacing the iso module as it is not available easily for SL5.
