### ISSUE TITLE
Can't call apel.db.backends.mysql.get_records() for CloudRecords

### ISSUE THREAD

**Issue by gregcorbett** [apel/apel#193]
I have created a [test case](https://github.com/gregcorbett/apel/blob/republish_fix_test/test/test_cloud_republish.py#L62) that illustrates the issue.

[Travis](https://travis-ci.org/gregcorbett/apel/jobs/548270794) error message:
```
======================================================================
ERROR: test_cloud_republish (test_cloud_republish.TestRepublish)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_cloud_republish.py", line 62, in test_cloud_republish
    database.get_records(apel.db.records.cloud.CloudRecord)
  File "/home/travis/build/gregcorbett/apel/apel/db/backends/mysql.py", line 189, in get_records
    for batch in self._get_records(record_type, select_query, rec_number):
  File "/home/travis/build/gregcorbett/apel/apel/db/backends/mysql.py", line 226, in _get_records
    record.set_all(row)
  File "/home/travis/build/gregcorbett/apel/apel/db/records/record.py", line 91, in set_all
    raise InvalidRecordException('Unknown field: %s' % key)
apel.db.records.record.InvalidRecordException: Unknown field: MeasurementMonth
```

Given that the `Measurement{Month, Year, Time}` are database only fields, I'm not sure the best way to fix this...

**Comment by tofu-rocketry** [comment]
I think the issue is that the measurement time fields ([`MeasurementTime, MeasurementMonth, MeasurementYear`](https://github.com/apel/apel/blob/9476bd86424f6162c3b87b6daf6b4270ceb8fea6/schemas/cloud.sql#L518)) aren't specific in the [Python `CloudRecord` definition](https://github.com/apel/apel/blob/dev/apel/db/records/cloud.py#L32).

**Comment by gregcorbett** [comment]
We reckon putting the variables in self._db_fields is sufficient, can't remember off the top of our heads if the order of that list matters.

**Comment by gregcorbett** [comment]
So putting them in `self._db_fields` like this [1] caused a problem [2] because the Measurement values are then passed to the MySQL `ReplaceCloudRecord` function (which we don't want them to be) and then Python rightly complains that not all arguments are converted during string formatting.

Treating them in the same fashion as `UpdateTime` [3], which kinda makes sense because `UpdateTime` and the Measurement values are created in the database, allows records to be loaded and unloaded, but this means the Measurement values don't get unloaded so doesn't help writing a test for #194.

:confounded:

[1]
```
self._db_fields = self._msg_fields[:9] + ['VO', 'VOGroup', 'VORole'] + self._msg_fields[9:12] + ["MeasurementTime", "MeasurementMonth", "MeasurementYear"] + self._msg_fields[12:]
```

[2] 
```
======================================================================
ERROR: test_cloud_republish (__main__.TestRepublish)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_cloud_republish.py", line 52, in test_cloud_republish
    database.load_records(record_list, source="testDN")
  File "/home/fnv21031/apel/apel/db/backends/mysql.py", line 166, in load_records
    c.execute(proc, values)
  File "/usr/lib64/python2.7/site-packages/MySQLdb/cursors.py", line 187, in execute
    query = query % tuple([db.literal(item) for item in args])
TypeError: not all arguments converted during string formatting
```

[3]
```
self._db_fields = self._msg_fields[:9] + ['VO', 'VOGroup', 'VORole'] + self._msg_fields[9]
...
self._ignored_fields = [
    "UpdateTime", "MeasurementTime", "MeasurementMonth",
    "MeasurementYear",
]
```

**Comment by tofu-rocketry** [comment]
Ok, `_ignored_fields` seems to make more sense - you'll just have to query the table directly to check the Measurement values.
