### ISSUE TITLE
Remove CloudType from CloudSummaries primary key

### ISSUE THREAD

**Issue by gregcorbett** [apel/apel#246]
From the [GGUS ticket](https://ggus.eu/index.php?mode=ticket_info&ticket_id=151118) (atleast), with CloudType being part of the [CloudSummaries table primary key](https://github.com/apel/apel/blob/dev/schemas/cloud.sql#L181), we end up having stale summaries because the CloudType (i.e. the verison of caso used to extract the records) can change on a republish.

To alleviate this, we could remove CloudType from the primary key. 

Given that CloudComputeServiceID is also in the CloudSummaries primary key and is grouped on by the summariser, I can't think of a down side.

**Comment by tofu-rocketry** [comment]
Looking at #250, had one query - should we leave the `CloudType` column as `NOT NULL`? It's required if it's in the primary key, but what impact does it have for us otherwise?

**Comment by gregcorbett** [comment]
It looks like `CloudType` could be `NULL` in the [Cloud Accounting Record](https://wiki.egi.eu/w/index.php?title=Federated_Cloud_Technology&oldid=102279), so it should probably be null-able in DB. 

Not sure if it would have an impact on us... does the portal ever group things by CloudType?
