### ISSUE TITLE
Faulty release 1.9.3-1

### ISSUE THREAD

**Issue by kreczko** [apel/apel#361]
The changes detailed in https://github.com/apel/apel/releases/tag/1.9.3-1 are not included in the release.

E.g. https://github.com/apel/apel/pull/316 was merged long time ago but the old version is still present in https://github.com/apel/apel/blob/1.9.3-1/apel/db/backends/oracle.py#L64 which is included in the source archive.

These files:
```
apel/db/backends/oracle.py 
apel/db/loader/aur_parser.py 
apel/db/loader/car_parser.py 
apel/db/loader/star_parser.py 
apel/ldap/query.py
```
are present with their `except Exception, e:` versions. Is this due to the `dev` and `master` discrepancy that they were missed?

**Comment by tofu-rocketry** [comment]
Thanks for checking this. However, #316 didn't touch any of the files you listed, so having some `except Exception, e:` remaining in 1.9.3 isn't unexpected. That PR was done as an opportunistic tidy up during HEPscore benchmarking work so only considered files relevant to that.

In terms of updating the rest of the code, #354 was a comprehensive tidy up, which should have converted the remaining ones (257d296dd03b094f386274e32bd9ccf3d81da7b5). That was merged recently and will be in the next release, currently planned as 2.0.0.
