### ISSUE TITLE
LDAP returns byte and not string with python3

### ISSUE THREAD

**Issue by vokac** [apel/apel#375]
Apel client fails with exception when tries to use `startswith` with string argument on items returned from LDAP, because they have different data type (array of bytes). This prevents publishing accounting data in the EGI monitoring.

Is this still official tool for publishing EGI accounting data or we missed some announcement and it is necessary to use different tool with python3?

**Comment by vokac** [comment]
btw: without too much thinking I "fixed" our client with
```patch
diff --git a/apel/ldap/query.py b/apel/ldap/query.py
index ba27ee2..f4c2569 100644
--- a/apel/ldap/query.py
+++ b/apel/ldap/query.py
@@ -79,13 +79,14 @@ def fetch_specint(site, host='lcg-bdii.egi.eu', port=2170):
     for entry in data:
 
         try:
-            ce_name = entry[1][GLUE_CE_UNIQUE_ID][0]
+            ce_name = entry[1][GLUE_CE_UNIQUE_ID][0].decode('utf-8')
             ce_capabilities=entry[1][GLUE_CE_CAPABILITY]
         except (KeyError, IndexError) as e:
             log.error('Error during fetching Spec values: %s', e)
             continue
 
         for capability in ce_capabilities:
+            capability = capability.decode('utf-8')
             si2k = parse_ce_capability(capability)
             if si2k is not None:
                 log.debug('Found value in first query: %s',
@@ -102,8 +103,8 @@ def fetch_specint(site, host='lcg-bdii.egi.eu', port=2170):
 
     for item in data:
         try:
-            cluster_name = item[1][GLUE_CHUNK_KEY][0].split('=')[1]
-            value = Decimal(item[1][GLUE_HOST_BENCHMARK][0])
+            cluster_name = item[1][GLUE_CHUNK_KEY][0].decode('utf-8').split('=')[1]
+            value = Decimal(item[1][GLUE_HOST_BENCHMARK][0].decode('utf-8'))
         except (KeyError, IndexError) as e:
             log.error('Error during fetching Spec values: %s', e)
             continue
@@ -120,10 +121,11 @@ def fetch_specint(site, host='lcg-bdii.egi.eu', port=2170):
                 continue
 
             for fk in fks:
+                fk = fk.decode('utf-8')
                 if fk.startswith(GLUE_CE_UNIQUE_ID):
                     name = fk.split('=')[1]
                     # do not overwrite values from first query
-                    if not any(x[0] == name for x in values):
+                    if len([x for x in values if x[0] == name]) == 0:
                         values.append((name, value))
 
     return values
```

**Comment by tofu-rocketry** [comment]
Thanks for the report and the suggested path. @Sae126V is looking at this now.

**Comment by tofu-rocketry** [comment]
> Is this still official tool for publishing EGI accounting data or we missed some announcement and it is necessary to use different tool with python3?

Sorry to not reply to your specific question. APEL is still the official tool, but it looks like we missed this in the wide-ranging work we were doing to update everything to Python 3. We will work to get the fix merged and released as swiftly as we can, but a workaround is to set the benchmarks locally in the client config: https://github.com/apel/apel/blob/2.0.0-1/conf/client.cfg#L28

**Comment by vokac** [comment]
Thanks, I was not aware of #186 which can be used to avoid LDAP dependencies

**Comment by norealroots** [comment]
An update, @Sae126V has https://github.com/apel/apel/pull/376 which will fix this issue.
@tofu-rocketry and Saiteja are targeting to release an APEL update including this by the end of the month.

**Comment by vokac** [comment]
New version 2.1.0 works with our configuration.
