### ISSUE TITLE
Implement V0.4 of the Cloud Schema

### ISSUE THREAD

**Issue by stuartpullinger** [apel/apel#71]
The updated cloud schema is described here:

https://oerc.basecamphq.com/F199381047

We need to implement:
- [x] Benchmark and BenchmarkType fields
- [x] subsite level
- [ ] Checking on ImageID field?

**Comment by tofu-rocketry** [comment]
SP's code pulled onto `cloud-0.4` blanch in #81.

**Comment by jcgordon** [comment]
Test comment.

**Comment by tofu-rocketry** [comment]
Related RT ticket: https://rt.egi.eu/rt/Ticket/Display.html?id=7590
