### ISSUE TITLE
Add PID check to summariser

### ISSUE THREAD

**Issue by stuartpullinger** [apel/apel#79]
The apel loader and ssm receiver bin scripts check for the existence of a PID file before running and fail if it exists. The summariser bin script does not do this. It is therefore possible to have 2 summarisers running at the same time. We should incorporate the check in the summariser so that this does not happen.

**Comment by gregcorbett** [comment]
@tofu-rocketry, I can look into this?

**Comment by tofu-rocketry** [comment]
I made a start on it but kept it local. I've just pushed my work to my repo on `summariser-pid-check` if you want to go from there.
