### ISSUE TITLE
Empty storage record crashes loader with wrong message

### ISSUE THREAD

**Issue by stuartpullinger** [apel/apel#85]
https://github.com/apel/apel/blob/dev/apel/db/loader/star_parser.py#L54

When an empty, but valid xml, storage record is loaded an exception is raised. The exception is not caught so it crashes the loader. We should move the empty message to the reject queue and continue.

**Comment by stuartpullinger** [comment]
And the message relates to CAR records not StAR records.

**Comment by tofu-rocketry** [comment]
The bug seems to be that a generic `Exception` is raised, which doesn't match any of the [caught exceptions in `loader.py`](https://github.com/apel/apel/blob/dev/apel/db/loader/loader.py#L157).

I'll change the exception type and check the other XML parsers.

**Comment by stuartpullinger** [comment]
Happy for you to close the issue once the issue #92 is merged.
